# Copyright 2022 Google LLC
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle-deployment
  namespace: moodle
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: moodle
      app.kubernetes.io/name: moodle
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: moodle
        app.kubernetes.io/name: moodle
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        # cloud.google.com/compute-class: "Balanced"
        # supported-cpu-platform.cloud.google.com/Intel_Ice_Lake: "true"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: moodle
                  app.kubernetes.io/name: moodle
              namespaces:
              - moodle
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - name: moodle
        image: southamerica-east1-docker.pkg.dev/<your-project-id>/<your-artifact-registry-name>/<image-name>:<tag> # make sure to differ moodle-nginx from moodle-bitnami
        imagePullPolicy: IfNotPresent
        ports:
        - name: moodle-port
          containerPort: 8080
        env:
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: moodle-externaldb
              key: mysql-password
        - name: MOODLE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: moodle-admin-password
              key: moodle-password
        - name: MOODLE_URL
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: MOODLE_URL
        - name: MOOSH_URL
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: MOOSH_URL
        - name: LANG
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: LANG
        - name: LANGUAGE
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: LANGUAGE
        - name: MOODLE_LANGUAGE
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: MOODLE_LANGUAGE
        - name: SITE_URL
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: SITE_URL
        - name: MOODLE_DATAROOT_PATH
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: MOODLE_DATAROOT_PATH
        - name: MOODLE_PATH
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: MOODLE_PATH
        - name: DB_TYPE
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: DB_TYPE
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: DB_HOST
        - name: DB_HOST_PORT
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: DB_HOST_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: DB_USER
        - name: DB_PREFIX
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: DB_PREFIX
        - name: MOODLE_SITENAME
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: MOODLE_SITENAME
        - name: MOODLE_SITESUMMARY
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: MOODLE_SITESUMMARY
        - name: MOODLE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: MOODLE_USERNAME
        - name: MOODLE_EMAIL
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: MOODLE_EMAIL
        - name: DB_READ_REPLICA_HOST
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: DB_READ_REPLICA_HOST
        - name: DB_READ_REPLICA_PORT
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: DB_READ_REPLICA_PORT
        - name: DB_READ_REPLICA_USER
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: DB_READ_REPLICA_USER
        - name: DB_READ_REPLICA_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: DB_READ_REPLICA_PASSWORD
        - name: REDIS_SESSION_ID_HOST
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: REDIS_SESSION_ID_HOST
        - name: REDIS_SESSION_ID_PORT
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: REDIS_SESSION_ID_PORT
        - name: REDIS_SESSION_ID_AUTH_STRING
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: REDIS_SESSION_ID_AUTH_STRING
        - name: REDIS_APP_IP_AND_PORT
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: REDIS_APP_IP_AND_PORT
        - name: REDIS_APP_AUTH_STRING
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: REDIS_APP_AUTH_STRING
        - name: REDIS_SESSION_IP_AND_PORT
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: REDIS_SESSION_IP_AND_PORT
        - name: REDIS_SESSION_AUTH_STRING
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: REDIS_SESSION_AUTH_STRING
        - name: REDIS_LOCK_HOST_AND_PORT
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: REDIS_LOCK_HOST_AND_PORT
        - name: REDIS_LOCK_AUTH_STRING
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: REDIS_LOCK_AUTH_STRING
        - name: SSLPROXY
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: SSLPROXY
        - name: NOEMAIL_EVER
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: NOEMAIL_EVER
        - name: SMTP_HOST
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: SMTP_HOST
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: SMTP_PORT
        - name: SMTP_USER
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: SMTP_USER
        - name: SMTP_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: SMTP_PASSWORD
        - name: SMTP_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: SMTP_PROTOCOL
        - name: MOODLE_MAIL_NOREPLY_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: MOODLE_MAIL_NOREPLY_ADDRESS
        - name: MOODLE_MAIL_PREFIX
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: MOODLE_MAIL_PREFIX
        # livenessProbe:
        #   failureThreshold: 60
        #   httpGet:
        #     path: /login/index.php
        #     port: 8080
        #   initialDelaySeconds: 600
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 5
        # readinessProbe:
        #   failureThreshold: 6
        #   httpGet:
        #     path: /login/index.php
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 5
        #   successThreshold: 1
        #   timeoutSeconds: 3
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 1Gi
        volumeMounts:
        - name: moodleroot-vol
          mountPath: /moodleroot/moodle
          subPath: moodleroot/moodle
        - name: moodleroot-vol
          mountPath: /moodleroot/moodledata
          subPath: moodleroot/moodledata
        - name: moodleroot-vol
          mountPath: /etc/nginx
          subPath: etc/nginx
        - name: moodleroot-vol
          mountPath: /etc/php81
          subPath: etc/php81
        - name: tmp-vol
          mountPath: /tmp
      volumes:
      - name: moodleroot-vol
        persistentVolumeClaim:
          claimName: pvc-filestore
      - name: tmp-vol
        emptyDir:
          medium: Memory
